# Generated by Django 4.2.1 on 2023-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='unique_title',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
