# Generated by Django 4.2.1 on 2023-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_unique_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='images',
            field=models.JSONField(max_length=200),
        ),
    ]
